### ISSUE TITLE
SonarQuest FE / Gamemaster / Quests

### ISSUE THREAD

**Issue by ithinkispider** [viadee/sonarQuest#105]
Editing the Quests offers a Textarea for the story of max 256 charakter.
In Viewmode the Grid of the Table starts overlapping the column 'adventure', if using more then 10 lines of text in the description.

Suggestion: Limit the view to eg. 100 charakter summary and make it a link opening a Popup similar to the editing dialog for full view.

**Comment by Christoph-Meyer** [comment]
Fixed in Release 0.5.1
