### ISSUE TITLE
SonarQuest FE / Quests / Quest view / My Quests / Minor

### ISSUE THREAD

**Issue by ithinkispider** [viadee/sonarQuest#118]
The Quest view contains a table Grid as follows:
Titel | Gold | XP | Story | Abenteuer | Status | 

The Lens Icon providing the Link to the Questdetail Dialog Popup seems to be part of the 'Status' Column or is at least displayed as if it was.
In case a Quest is **SOLVED** the 'D' and the Icon overlap.

As both Items (String and Icon) refer a Link the overlapping means a little inconvenience.
Nonetheless both functions are accessible.

Reproducable on 19'' and 24'' eg. in Chrome 67.0.3396.99, FF Quantum 61.0.1, vivaldi 1.15.1147.52

**Comment by Christoph-Meyer** [comment]
Also, changed the icon of the lens to sth much cooler and added a tooltip.
