### ISSUE TITLE
SonarQuest FE / All views / Top Menu bar / minor

### ISSUE THREAD

**Issue by ithinkispider** [viadee/sonarQuest#132]
Enhence the Menu by Hoover-Effects that indicate a function.
Provide Tool-Tips. 
e.g The bolt like icon left of the logout does not explain the toggle background function.
Maybe enhence that function / menu. refer to #129

**Comment by Christoph-Meyer** [comment]
Basic ui functionality - you are right, that should be implemented.

**Comment by Christoph-Meyer** [comment]
Was fixed in the tooltipp issue #127 

Closing this one.
