### ISSUE TITLE
Adventures cannot be deleted

### ISSUE THREAD

**Issue by Christoph-Meyer** [viadee/sonarQuest#142]
Bug: Adventures can not be deleted in the GM ui. The button to delete them is missing (although the service exists).

**Comment by Christoph-Meyer** [comment]
The button has been added but the deletion does not work properly. This needs to be checked again, probably multiple bugs here:

To test:
- New adventure, add a quest, save, delete adventure => Nothing happens
- New adventure, add a quest, save, open, delete the quest from the adventure, save, delete adventure => Nothing happens

**Comment by Christoph-Meyer** [comment]
Did some more testing: in some cases it does seem to work and it looks like this could be only a "refresh" issue in the UI.

Backend log read: 
2019-04-26 13:03:49.001  INFO [sQ,9b25232963072966,9b25232963072966,false] 11636 --- [nio-8080-exec-7] c.v.s.controllers.AdventureController    : Deleted adventure with id 35

and after klicking around in the GM UI, the adventure actually did disappear.

**Comment by surfermicha** [comment]
Seems to work. Please reopen, if you encounter further problems relating to this issue.
