### ISSUE TITLE
After a successful login, show the 'my avatar' page

### ISSUE THREAD

**Issue by Christoph-Meyer** [viadee/sonarQuest#150]
Just like the title says - instead of a blank white screen, show the avatar page after logging in.

**Comment by cucina-md** [comment]
Refer to #120.
Making 'myAvatar' the default for a sucessful login would solve my mainIssue in #120.
But consider meaningful content for an errorpage or an useful redirect to the login dialogue.

Also refer to #124 claiming a non-white-page design for the start/login page as well :).

**Comment by Christoph-Meyer** [comment]
Okay, sounds resonable. I will look into it.

**Comment by Christoph-Meyer** [comment]
Done :)

**Comment by ithinkispider** [comment]
I trust you on this one ... :)
