### ISSUE TITLE
Party of developers

### ISSUE THREAD

**Issue by Christoph-Meyer** [viadee/sonarQuest#170]
It would be a real cool feat if two or more developers could form a "party" and go on questing together. The gm could create a party and assign players to it and in the player's UI there could be a list of parties to join.
A party could have the following cool features
- fancy name
- min/max number of developers who can join
- banner picture 
- list of the last 5 quests the party members survived
- a list where each player avatar can be seen who is in that party.

I am sure this feature could be expanded to even to party vs. party questing (a feature requested long ago) or to implement a party-based "competition ladder".

Opinions?

**Comment by fkoehne** [comment]
Let's get Nicolas in on this discussion.

**Comment by surfermicha** [comment]
doubles #227
