### ISSUE TITLE
Oracle keyword inside table name.

### ISSUE THREAD

**Issue by Diazed** [viadee/sonarQuest#174]
I tired to start sonarquest with a oracle DB. 
SonarQuest is unable to start because "level" is one of the reserved words in oracle.
See: https://docs.oracle.com/cd/A97385_01/appdev.920/a42525/apb.htm

**Comment by Diazed** [comment]
Forgot to mention that "user" is reserved in Oracle as well.

**Comment by Christoph-Meyer** [comment]
https://docs.oracle.com/cd/E11882_01/server.112/e41084/ap_keywd001.htm#SQLRF55621

Oracle reference for reserved words. Well I guess to make it work we will need to change some table names or quote them.

**Comment by fkoehne** [comment]
Let's talk about that - I can provide one, if you want.

**Comment by aabeling** [comment]
How about using an oracle db in a docker container: 
https://hub.docker.com/_/oracle-database-enterprise-edition
https://github.com/oracle/docker-images

**Comment by fkoehne** [comment]
Interesting idea. However, we created an Oracle schema yesterday evening and can run our tests there. I think that should do it to get rid of the reserved words and prove that its all working.
I think that, generally speaking, the Spring stack can be trusted to work across databases and we don't need to create a dockerized matrix-build of different databases and database versions right away. 
... unless someone would send a pull request :).

Ticket remains open. Renaming and testing still need to happen.

**Comment by Christoph-Meyer** [comment]
I started the renaming yesterday night but it I am not finished yet.

"User" will be "Player" in the future and "Level" will be "PlayerLevel".

**Comment by Christoph-Meyer** [comment]
Renaming done - should work now.

Still needs testing to be closed.
