### ISSUE TITLE
Reloading Page leads to 404

### ISSUE THREAD

**Issue by piadiedam** [viadee/sonarQuest#199]
When reloading a page, one is redirected to a 404-error. 

(Probably due to a wrong mapping to empty)

**Comment by Christoph-Meyer** [comment]
Happens only as a logged-in user?

**Comment by surfermicha** [comment]
Is this still open? I cannot reproduce it. When exactly does that happen? I guess this should have been solved already. 
_Note: The redirect commands have changed in issue #124_

**Comment by surfermicha** [comment]
In order of inactivity I will close this issue. Please reopen if you have any further problems related to this issue
