### ISSUE TITLE
Marketplace for gamemasters

### ISSUE THREAD

**Issue by bm-viadee** [viadee/sonarQuest#2]
As a gamemaster I want to create and select artifacts for the marketplace

Create an artifact:
- [x] name
- [x] picture
- [x] description
- [x] enhancements (rule engine needs to be implemented)

Select an artifact for the marketplace
- [x] select one artifact
- [x] set price 
- [x] set available quantity

**Comment by fkoehne** [comment]
What does selection mean in this context? Does a gamemaster maintain a pool of artifacts, that are not visible for others?

**Comment by Christoph-Meyer** [comment]
Already added and partially reworked in
https://github.com/viadee/sonarQuest/commit/a0e1c54152d45e9f35060af3021bd3cf37dec4e7
