### ISSUE TITLE
Unable to select active world 

### ISSUE THREAD

**Issue by aZr43l** [viadee/sonarQuest#214]
Hi, I just tried out Sonar Quest for the first time and am struggling to get it up and running. 

I set the sonarqube url under admin->sonarqube and updated the worlds. After activating some of them, I switched to Developers and edited some of the default players with role "DEVELOPER" and checked the "Joined" checkbox for the active worlds.

But the selectbox where I am supposed to choose the active world is still empty. The wizard still says: "No active world selected: In the top left menu item select your preferred world to get even more hints from the wizard! If that is not possible the admin has to activate players for that world first"

Any help would be appreciated.

**Comment by Christoph-Meyer** [comment]
Hi and thanks for reporting this. We will look into the issue but in the meantime there is a workaround. You can probably solve the issue by assigning the world to the administrator account first, then logging out and in again and then assigning the world to the players.
Can you try that for me, please?

**Comment by aZr43l** [comment]
Ok, the workaround did the trick. Now I can select the active world. 

Thanks for the help.

**Comment by Christoph-Meyer** [comment]
Good to know - we will look into fixing the underlying issue nonetheless. 
Have fun with SonarQuest!
