### ISSUE TITLE
Basic auth is not saved

### ISSUE THREAD

**Issue by shawly** [viadee/sonarQuest#253]
Adding HTTP Basic Authentication does not work since it's not saved, which prevents scanning of private projects in SonarQube since the user is not logged in.
If the SonarQube is configured to force log in under Security settings, then authentication doesn't work at all.

**Comment by shawly** [comment]
Sorry, messed up my commits. But your build system doesn't seem to work, could you take a look?

**Comment by surfermicha** [comment]
Is fixed
