### ISSUE TITLE
SonarQube Api Call https://sonarcloud.io/api/components/search to generate Worlds no longer works

### ISSUE THREAD

**Issue by Kalinow** [viadee/sonarQuest#259]
Hey team,

i have noticed that the SonarQube API Call: https://sonarcloud.io/api/components/search?qualifiers=TRK&pageSize=500&pageIndex=1 to generate Worlds no longer works. 

I get an Http 400 Error with the msg "The 'organization' parameter is missing".

Does anybody have the same Problem? 

I would then add the organization attribute to the api call 
(+ Adding a field in the admin mask to set the organization attribute)

An other solution is to use the following api https://sonarcloud.io/web_api/api/projects (also with parameter organization)

Thanks for help! :)

**Comment by Christoph-Meyer** [comment]
Hi @Kalinow , 

nice catch! Could you please issue the fix as a separate Pull Request, so I can add it to the master branch? That would be really helpful!

**Comment by Kalinow** [comment]
@Christoph-Meyer , yes of course
