### ISSUE TITLE
When saving new entities no ID is returned

### ISSUE THREAD

**Issue by Christoph-Meyer** [viadee/sonarQuest#29]
When saving a new entity with the Spring Data Crud repository, after the INSERT an entity with an ID value should be returned. The ID is null, however.

Idea: Might be because of the DB using AUTO_INCREMENT instead of Spring Data @Id Annotation (with explicit generation strategy) in the Entities. Needs to be checked.

**Comment by aabeling** [comment]
I cannot reproduce this (tried with the WorldRepository).
Does the problem still exist?
Which entities are affected?

**Comment by Christoph-Meyer** [comment]
I also tried it again with 
- UserRepo and
- AdventureRepo
but I could not reproduce it.

I will close this issue for now.
