### ISSUE TITLE
Gamemaster cannot create new standard tasks

### ISSUE THREAD

**Issue by Christoph-Meyer** [viadee/sonarQuest#31]
Steps to reproduce: Frontend -> Gamemaster -> Tasks -> New Standard Task (Button)
Result: nothing happens
Desired: Pop-up dialogue, just like "New Special Task".

**Comment by sdibernardo** [comment]
Feedback would be appreciated, as this is a little tricky.
The TaskDto class is getting deserialized as SpecialTaskDto. That does screw up the StandardTaskDto as a deserialization exception gets thrown. We have to find a proper way to deserialize both Dtos. Suggestions are appreciated. Code can be found in the branch "issue31"

**Comment by Christoph-Meyer** [comment]
Testing...

**Comment by Christoph-Meyer** [comment]
Just checked it - yep, definately JS UI issue. Ctrl + F5 does the trick...

**Comment by sdibernardo** [comment]
Should we do something about it?

**Comment by Christoph-Meyer** [comment]
Yes, please - could you talk to @CINO-DE he might know how to trigger a refresh there.

**Comment by sdibernardo** [comment]
done in  #78

**Comment by Christoph-Meyer** [comment]
To be precise:
Tasks come in two different flavours, special & standard. Standard tasks can ONLY be retrieved via the SonarQube server. Special tasks can be created freely.

Issue no longer relevant. Closed.
