### ISSUE TITLE
Typo in banner: "technical debt", not "dept"

### ISSUE THREAD

**Issue by david-cho-lerat-sonarsource** [viadee/sonarQuest#341]
In https://github.com/viadee/sonarQuest/blob/master/docs/images/sonarquest-banner.png, the message should read "Fight your technical debt"
("dept" is also mentioned in https://github.com/viadee/sonarQuest/wiki, and maybe other places?)

**Comment by Christoph-Meyer** [comment]
Took a while, but I fixed it. TY
