### ISSUE TITLE
Change the level attribute of the entity developer from type  "level " to "long"

### ISSUE THREAD

**Issue by CINO-DE** [viadee/sonarQuest#37]

**Comment by fkoehne** [comment]
Can you please explain the idea and your reasoning?

**Comment by CINO-DE** [comment]
We want to save the level as long in the user entity. The Classe level has attributes that we don't need.

**Comment by sdibernardo** [comment]
The models haven been altered by me for #79, so the sql script creating the schema conforms to the backend. IDs are consistently Long/BigInteger now. Please check if this issue can be closed in the newest version

**Comment by Christoph-Meyer** [comment]
The level system has been reworked by @bm-viadee.
Issue is no longer relevant. 
Closed.
