### ISSUE TITLE
Show error message when there is no connection with the SonarQube server

### ISSUE THREAD

**Issue by Christoph-Meyer** [viadee/sonarQuest#5]
There is actually an exception, but it does not give a proper message and is not shown.

**Comment by h-huss** [comment]
Do you want a better exception on startup or a message in the frontend?

**Comment by Christoph-Meyer** [comment]
A message in the frontend was what I had in mind.

**Comment by h-huss** [comment]
A message in the frontend is very similar to #4.  Currently the server refuses to start if there is no connection to the backend - the frontend has no way of knowing why their web call failed. 

I would make #4 about better error handling: Showing in the frontend the cases a) the server is not running and b) The server delivered a 50X error - check the logs.

This Issue then amounts to a better backend error message on missing sonar server.
