### ISSUE TITLE
Bug: RestTemplate does not work with current SonarQube-API

### ISSUE THREAD

**Issue by Christoph-Meyer** [viadee/sonarQuest#51]
The API has been changed, this needs to be included in the matching Rest-Template.

**Comment by Christoph-Meyer** [comment]
Currently the issues from SonarQube cannot be pulled, this should be fixed asap.

**Comment by Christoph-Meyer** [comment]
I see if I can fix this myself.

**Comment by fschacht04** [comment]
We have to make a "rest-call-loop" to the api as they introduced paging with a max size of 500 issues per page...i am currently trying to adjust the template and the corresponding "get-issues" logic

**Comment by bm-viadee** [comment]
HTTP authentication is now mandatory when using the Sonar REST API (which is a wise decision anyways). 

- account data must be added to SonarCube configuration
- all REST-calls must use authentication beforehand (see: https://docs.sonarqube.org/display/DEV/Web+API )
- check if api-calls still work after the update (only available list of endpoints here: https://docs.sonarqube.org/pages/viewpage.action?pageId=2392181 - should be the same paths...)
-

**Comment by sdibernardo** [comment]
- Single SonarQube Server for each SonarQuest Backend
- Configuration via Beans
- Bean Injection via application.properties (#25)
- SonarQuest Backend will start regardless of SonarQube availability (Indicator for UI)

**Comment by Christoph-Meyer** [comment]
Works fine now. Closed.
