### ISSUE TITLE
Background image depending on the world

### ISSUE THREAD

**Issue by CINO-DE** [viadee/sonarQuest#60]

**Comment by fkoehne** [comment]
This looks really promising. :)

Please remember to fix the demo image on the frontpage as well, when you are done here.
We should also update the screenshots here: https://www.viadee.de/sonarquest/ - maybe you can talk to @ChristianDieckhoff about the choice of background images and image licences beforehand?

**Comment by Christoph-Meyer** [comment]
Done - the bg image is now choosable in the admin area when creating a world from the sonarqube data.

Also, all images are licence-free versions.
