### ISSUE TITLE
As a gamemaster, I can use an image for a quest in order to illustrate it more lively

### ISSUE THREAD

**Issue by fkoehne** [viadee/sonarQuest#7]

**Comment by TamaraGunkel** [comment]
Should we provide standard images, allow gamemasters to upload own images or let them insert a link/url to the image?

**Comment by fkoehne** [comment]
... in this order please :). Let's start with a set of predefined images to choose.

**Comment by TamaraGunkel** [comment]
Do we already have images or where can I get some?

**Comment by fkoehne** [comment]
We can start with these guys here https://blog.viadee.de/abschlussarbeit-sonarquest.

**Comment by CINO-DE** [comment]
nice (Y)
