### ISSUE TITLE
As an admin, i can create, update and delete developers, in order to manage my teams

### ISSUE THREAD

**Issue by CINO-DE** [viadee/sonarQuest#8]

**Comment by fkoehne** [comment]
I think we should not delete developers physically. This would lead to all kinds of inconsistencies - most of all, members of past quests would disappear, i.e. the "memory of the team" would be changed, which I would consider a no-go.
Let's implement a logic deletion and remove all personal data (like mail adresses etc. ) as far as we have them.

**Comment by Christoph-Meyer** [comment]
Feature has been implemented long ago - closing this task now.
