### ISSUE TITLE
Missing file or wrong url

### ISSUE THREAD

**Issue by CINO-DE** [viadee/sonarQuest#83]
You will get a 404, if you click at the README.md file (text on https://github.com/viadee/sonarQuest ) on the blue LICENSE.md link

**Comment by h-huss** [comment]
Either the file LICENSE needs to be renamed to LICENSE.md, or the link needs to go to LICENSE, without md.

Any preferences?

**Comment by Christoph-Meyer** [comment]
The second one is just fine.

**Comment by sdibernardo** [comment]
Done
