### ISSUE TITLE
SonarQuest FE / Login Dialog / EnterKey

### ISSUE THREAD

**Issue by ithinkispider** [viadee/sonarQuest#92]
Logindialog cannot be completed using the  'ENTER' - Key
- Accessing the Frontend on a local installation (http://localhost:4200/empty)
- open Login Dialog by 'hitting' Login-Button
- Enter: _username_ -> 'TAB' -> _password_ -> 'ENTER'

'ENTER' does not work.
You have use the 'OK'-Button of the Form.

Providing a KEY - Feature would be nice.

**Comment by ithinkispider** [comment]
Update: Focusing the 'OK' - Button by hitting 'TAB' 'TAB' first, enables use of the 'ENTER' -Key.

**Comment by bm-viadee** [comment]
Fixed in Release 0.2.4
